Eina: add affinity to win32 code.
It's not working yet:
 * eina_thread.c:152:33: error: 'index' undeclared (first use in this function)
 * eina_thread.c:295:4: warning: passing argument 3 of '_eina_thread_win32_create' from incompatible pointer type [enabled by default]

also:

 * line 142, is it normal that we call eina_list_append() with tw being NULL ?
 * is what I did in the close_thread label correct ?


SVN revision: 78416