benchmarks: eine: include header for using time()
../src/benchmarks/eina/eina_bench_sort.c: In function ‘eina_bench_sort_eina’:
../src/benchmarks/eina/eina_bench_sort.c:52:10: warning: implicit declaration of function ‘time’ [-Wimplicit-function-declaration]
    srand(time(NULL));

Found due to the nice quite build output in our meson feature branch.