emotion: Fix missing include resulting in unknown type GstNavigationCommand
At least on the gstreamer1 version in Fedora 19 this include is needed. Glima
reported it as well and I think he also uses Fedora.

modules/emotion/gstreamer1/emotion_gstreamer.c:643:4: error: unknown type name
'GstNavigationCommand'

Even if other distros or gstreamer1 versions do not need this it should be safe
to add it here.