Revert "eina: add locale-independent eina_convert_strtod_c function"
This reverts commit bef1c5cc433b89add2cf0292e1098e1bd74ac640.

The commit breaks the build on macos. I gave it soem time to get fixed
up quickly, but its late Friday night in Korea now and this is unlikely
to get fixed until Monday. Revert here until fixed.

./src/lib/eina/eina_private.h:158:1: error: unknown type name 'locale_t'

https://travis-ci.org/Enlightenment/efl/jobs/461790674