sorry - have to revert this as this brings the efl tree build to a grinding halt - it wasn't great before.. but now it's totally broken. :( e.g.:
/bin/bash ../libtool  --tag=CC   --mode=link ccache gcc -std=gnu99
-O2 -g -pipe -march=native -fvisibility=hidden -ffast-math -W -Wall
-Wextra -Wno-shadow -Wno-unused-but-set-parameter   -o bin/eet/eet
bin/eet/bin_eet_eet-eet_main.o -fvisibility=hidden -fdata-sections
-ffunction-sections -Wl,--gc-sections -fno-strict-aliasing
-Wl,--as-needed -Wl,--no-copy-dt-needed-entries    lib/eet/libeet.la

libtool: link: ccache gcc -std=gnu99 -O2 -g -pipe -march=native
-fvisibility=hidden -ffast-math -W -Wall -Wextra -Wno-shadow
-Wno-unused-but-set-parameter -o bin/eet/.libs/eet
bin/eet/bin_eet_eet-eet_main.o -fvisibility=hidden -fdata-sections
-ffunction-sections -Wl,--gc-sections -fno-strict-aliasing
-Wl,--as-needed -Wl,--no-copy-dt-needed-entries  lib/eet/.libs/libeet.so
/usr/bin/ld: bin/eet/bin_eet_eet-eet_main.o: undefined reference to
symbol 'eina_iterator_next'
/usr/bin/ld: note: 'eina_iterator_next' is defined in DSO
/usr/local/lib/libeina.so.1 so try adding it to the linker command line
/usr/local/lib/libeina.so.1: could not read symbols: Invalid operation
collect2: ld returned 1 exit status



SVN revision: 83112