elput: add missing dependency on libudev
Elput is using udev directly so we need to amke sure we link against it.

lib/elput/.libs/lib_elput_libelput_la-elput_input.o: In function `_elput_input_init_thread':
/<<PKGBUILDDIR>>/src/lib/elput/elput_input.c:317: undefined reference to `udev_new'
/<<PKGBUILDDIR>>/src/lib/elput/elput_input.c:326: undefined reference to `udev_unref'

Patch by aerodynamik. Thanks!

Fixes T3712