configure: Link eina to librt. This is needed for shm_* calls
Recent clang breaks with linking errors:
lib/eina/.libs/libeina.so: undefined reference to `shm_open'
so fix.

Signed-off-by: Daniel Willmann <d.willmann@samsung.com>