efl.ui.textbox: part implementation comments clean up!
Summary:
We did not use the **ELM_PART_OVERRIDE_** because it produces compilation error

```
../src/lib/elementary/efl_ui_textbox.c:3603:40: error: ‘EFL_UI_TEXTBOX_PART_CLASS’ undeclared (first use in this function)
 ELM_PART_OVERRIDE_PARTIAL(efl_ui_text, EFL_UI_TEXTBOX, Efl_Ui_Textbox_Data, _part_is_efl_ui_text_part)
```

Reviewers: woohyun, bu5hm4n

Reviewed By: woohyun

Subscribers: segfaultxavi, cedric, #reviewers, #committers

Tags: #efl

Maniphest Tasks: T8522

Differential Revision: https://phab.enlightenment.org/D11102