hell no. printf. not eina-log. this is test exampels, not debug from an app. they printf as OUTPUT. alkso u broke build:
/home/raster/C/elm/src/bin/test_genlist.c:2862: undefined reference to
_elm_log_dom'

of course there is no symbol exposed that is an INTERNAL LOG DOMAIN to
elm! it's for elm not for outside.



SVN revision: 73957