Revert "image_savers/jpeg: actually use normal jmp_buf/setjmp/longjmp"
This reverts commit 5beb47aa4d65d0be9d75550511dd184e9e69b4d8.

Revert "image_savers/jpeg: fix undefined behavior of using sigsetjmp on jmp_buf"

This reverts commit 84c7751e195ea29efffbe55eaa732e739402a04a.

these end up with efl simply not compiling. efl tree does not build at
all now and this warrants a revert.

lib/evas/.libs/libevas.so: undefined reference to sigjmp'
collect2: error: ld returned 1 exit status
Makefile:19321: recipe for target 'bin/evas/evas_cserve2' failed
.. etc.