ci: travis: ensure we update brew as well to avoid a problem on Travis
We normally did not use update as it could take up a few minutes for
every macos build and the packages have been recent enough. Since a few
hours we see build problems now on Travis:
Error: Unknown command: bundle

A way to get them fixed (until Travis updates their images for macos) is
to use the update command.
https://travis-ci.community/t/macos-build-fails-because-of-homebrew-bundle-unknown-command/7296/9

Also moving to a newer osx image here to avoid falling further behind on
the dependencies.