Revert "Eolian CXX: Get rid of built sources for the callbacks test sources."
This reverts commit 638e72fda4bd312247c133038b26d8105315176f.

After this change the files did not end up in the tarball and failing make distcheck

../../src/tests/eolian_cxx/callback.c:11:25: fatal error: callback.eo.h: No such file or directory