benchmark: eo: add missing phthread flag to linker
/usr/bin/ld: class_simple.o: undefined reference to symbol 'pthread_spin_trylock@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line