Doc: Try to fix build on Ubuntu
The error message was:
/usr/bin/ld: preview_text_filter.o: undefined reference to symbol 'efl_gfx_filter_program_set'
//home/batden/Enlightenment20/efl/src/lib/efl/.libs/libefl.so.1: error adding symbols: DSO missing from command line