efl_ui_animation_view: change to Animation_View_State to resolve name conflict
Summary:
When cs file is generated, there is compiler error like
`Error CS0101 The namespace 'Efl.Ui' already contains a definition for 'AnimationView'`.
bacause `Efl.Ui.Animation_View` is class name, `Efl.Ui.Animation_View` can't be
namespace of `State` enum.

This patch will prevent name conflict between namesapce of enum and class name.

Test Plan: meson setup builddir -Dbindings=mono,cxx -Dmono-beta=true

Reviewers: Hermet, jsuya

Reviewed By: Hermet

Subscribers: cedric, #reviewers, #committers

Tags: #efl

Differential Revision: https://phab.enlightenment.org/D9555