ecore/drm: Compile ecore_drm_logind.c without condition
Right now we excluded the file from the build if we did not find system-logind.
We are using some symbols from this file without any condition though:
lib/ecore_drm/.libs/libecore_drm.so: undefined reference to `_ecore_drm_logind_device_open_no_pending'
lib/ecore_drm/.libs/libecore_drm.so: undefined reference to `_ecore_drm_logind_connect'
lib/ecore_drm/.libs/libecore_drm.so: undefined reference to `_ecore_drm_logind_disconnect'
lib/ecore_drm/.libs/libecore_drm.so: undefined reference to `_ecore_drm_logind_device_close'

This comes from a Gentoo machine without systemd.

As the logind relevant parts are ifdef'ed in the code itself it is safe to build
this file in all cases and thus avoid the undefined references.

@fix