dlopen and friends are now required by elm_need_e_dbus(), remove HAVE_FORK conditional to include the header.
Build was broken with the following message:

elm_main.c: In function 'elm_need_e_dbus':
elm_main.c:372:4: warning: implicit declaration of function 'dlopen' [-Wimplicit-function-declaration]
elm_main.c:372:46: error: 'RTLD_LAZY' undeclared (first use in this function)
elm_main.c:372:46: note: each undeclared identifier is reported only once for each function it appears in
elm_main.c:372:58: error: 'RTLD_GLOBAL' undeclared (first use in this function)
elm_main.c:374:4: warning: implicit declaration of function 'dlsym' [-Wimplicit-function-declaration]
elm_main.c:374:14: warning: assignment makes pointer from integer without a cast [enabled by default]
elm_main.c: In function '_elm_unneed_e_dbus':
elm_main.c:387:18: warning: assignment makes pointer from integer without a cast [enabled by default]
elm_main.c:392:4: warning: implicit declaration of function 'dlclose' [-Wimplicit-function-declaration]

I wonder if this is correct for other platforms other than linux??



SVN revision: 82573